#84: implemented likeroles feature
orwir/leeroy-discord-bot pull request #90
Opened 2020-11-26 22:13 UTC by Marzipans

Implemented likeroles feature

2020-11-26 22:20 UTC, Marzipans commented on src/features/system/command.js
> +    const separator = rawargs.indexOf(' ') < rawargs.indexOf('\n') ? ' ' : '\n'
In case when admin uses command without space in the end of lane, command will not be recognized (parsed like `$likeroles\n`

2020-11-27 01:27 UTC, orwir requested changes
Overall well enough. Only a couple of comments addresses real issues. The rest just about styling.

2020-11-27 01:27 UTC, orwir commented on src/features/management/likeroles.js
> +                description: elements.slice(2).join(' ') || ''
No need for the last part (`|| ''`). The frist part would never be null but an empty string in worst scenario.

2020-11-27 01:27 UTC, orwir commented on src/features/management/likeroles.js
> +        if (lines.length === 0) {
just `if (lines.length)`

2020-11-27 01:27 UTC, orwir commented on src/features/management/likeroles.js
> +            let description = obj.description
better use `const` instead of let if you don't have an intention to change these properties.

2020-11-27 01:27 UTC, orwir commented on src/features/management/likeroles.js
> +            var embed = path(msg, 'embeds[0]');
don't use `var`. Either `const` or `let`.

2020-11-27 01:27 UTC, orwir commented on src/features/management/likeroles.js
> +            emojis.forEach((emoji) => message.react(emoji))
reaction setting is an async operation. You should handle it properly.

2020-11-27 01:27 UTC, orwir commented on src/features/management/likeroles.js
> +            const role = await getRole(context.message, fields[idx + 1].value)
Do you really need to fetch all roles just to set only one specific?

2020-11-27 01:27 UTC, orwir commented on src/features/management/likeroles.js
> +			return;
too far away from the left

2020-11-27 17:54 UTC, orwir requested changes

2020-11-27 17:54 UTC, orwir commented on src/features/management/likeroles.js
> +            emojis.forEach(async (emoji) => await message.react(emoji))
use still doesn't handle it properly.

```js
return result.then(message => Promise.all([emojis.map(emoji => message.react(emoji));
```

2020-11-27 17:54 UTC, orwir commented on src/features/management/likeroles.js
> +                }
why you don't just break the cycle if you found requested emoji?

2020-11-27 21:13 UTC, orwir approved these changes

2020-11-27 21:14 UTC, merged